export const careerModsByRank = {
  commercial: {
    personalTraitsMods: {
      emotionMod: 0,
      fitMod: 0,
      instinctMod: 1,
      mindMod: 2,
      passionMod: 0,
      willMod: 0.5,
    },
    powerMods: {
      diplomaticMod: 0,
      economicMod: 3,
      militaryMod: 0,
      politicalMod: 0.5,
      socialMod: 1,
    },
    skillsMods: {
      artisticalMod: 0.5,
      phisycalMod: 0,
      intelectualMod: 0.5,
      martialMod: 0,
      nootericMod: 0,
      socialMod: 1,
      technicalMod: 1,
    },
    patrimonialBelongingsMods: {
      companies: 2,
      inmobiliary: 1,
      mobiliary: 1,
      valourObjects: 1,
    },
    equipmentMods: {
      armor: 0,
      weapons: 0,
      implants: 2,
    },
  },
  criminal: {
    personalTraitsMods: {
      emotionMod: 0,
      fitMod: 0.5,
      instinctMod: 0.5,
      mindMod: 1,
      passionMod: 0.5,
      willMod: 2,
    },
    powerMods: {
      diplomaticMod: 0,
      economicMod: 3,
      militaryMod: 1,
      politicalMod: 0,
      socialMod: 0.5,
    },
    skillsMods: {
      artisticalMod: 0.5,
      phisycalMod: 0,
      intelectualMod: 1,
      martialMod: 1,
      nootericMod: 0,
      socialMod: 0.5,
      technicalMod: 0.5,
    },
    patrimonialBelongingsMods: {
      companies: 0,
      inmobiliary: 1,
      mobiliary: 2,
      valourObjects: 2,
    },
    equipmentMods: {
      armor: 1,
      weapons: 1,
      implants: 2,
    },
  },
  gubernamental: {
    personalTraitsMods: {
      emotionMod: 0,
      fitMod: 0.5,
      instinctMod: 1,
      mindMod: 0.5,
      passionMod: 0,
      willMod: 1,
    },
    powerMods: {
      diplomaticMod: 1,
      economicMod: 0,
      militaryMod: 1,
      politicalMod: 2,
      socialMod: 0.5,
    },
    skillsMods: {
      artisticalMod: 0,
      phisycalMod: 0,
      intelectualMod: 1,
      martialMod: 1,
      nootericMod: 0,
      socialMod: 1,
      technicalMod: 1,
    },
    patrimonialBelongingsMods: {
      companies: 0,
      inmobiliary: 0,
      mobiliary: 1,
      valourObjects: 1,
    },
    equipmentMods: {
      armor: 0,
      weapons: 1,
      implants: 1,
    },
  },
  militar: {
    personalTraitsMods: {
      emotionMod: 0,
      fitMod: 2,
      instinctMod: 1,
      mindMod: 0.5,
      passionMod: 0,
      willMod: 1,
    },
    powerMods: {
      diplomaticMod: 0,
      economicMod: 0,
      militaryMod: 3,
      politicalMod: 1,
      socialMod: 0.5,
    },
    skillsMods: {
      artisticalMod: 0,
      phisycalMod: 1,
      intelectualMod: 0.5,
      martialMod: 2,
      nootericMod: 0,
      socialMod: 0.5,
      technicalMod: 0,
    },
    patrimonialBelongingsMods: {
      companies: 0,
      inmobiliary: 0,
      mobiliary: 1,
      valourObjects: 0,
    },
    equipmentMods: {
      armor: 2,
      weapons: 2,
      implants: 1,
    },
  },
  religous: {
    personalTraitsMods: {
      emotionMod: 1,
      fitMod: 0,
      instinctMod: 0.5,
      mindMod: 0.5,
      passionMod: 0.5,
      willMod: 1,
    },
    powerMods: {
      diplomaticMod: 0,
      economicMod: 1,
      militaryMod: 0.5,
      politicalMod: 1,
      socialMod: 1,
    },
    skillsMods: {
      artisticalMod: 1,
      phisycalMod: 0,
      intelectualMod: 1,
      martialMod: 0,
      nootericMod: 1,
      socialMod: 1,
      technicalMod: 0,
    },
    patrimonialBelongingsMods: {
      companies: 0,
      inmobiliary: 1,
      mobiliary: 0,
      valourObjects: 2,
    },
    equipmentMods: {
      armor: 0,
      weapons: 0,
      implants: 1,
    },
  },
  technical: {
    personalTraitsMods: {
      emotionMod: 0.5,
      fitMod: 0,
      instinctMod: 0,
      mindMod: 1,
      passionMod: 1,
      willMod: 1,
    },
    powerMods: {
      diplomaticMod: 0,
      economicMod: 0.5,
      militaryMod: 0,
      politicalMod: 0.5,
      socialMod: 3,
    },
    skillsMods: {
      artisticalMod: 1,
      phisycalMod: 0,
      intelectualMod: 2,
      martialMod: 0,
      nootericMod: 0,
      socialMod: 0,
      technicalMod: 2,
    },
    patrimonialBelongingsMods: {
      companies: 1,
      inmobiliary: 0,
      mobiliary: 0,
      valourObjects: 1,
    },
    equipmentMods: {
      armor: 0,
      weapons: 0,
      implants: 1,
    },
  },
};
