export const lenguaUbasharida = {
  diacritics: ['â', 'ê', 'î', 'ô', 'û', 'Â', 'Ê', 'Î', 'Ô', 'Û'],
  diacriticsMaxPerWord: 1,
  diacriticsReversal: {
    â: 'a',
    ê: 'e',
    î: 'i',
    ô: 'o',
    û: 'u',
  },
  vocals: ['a', 'e', 'i', 'o', 'u', 'uâ', 'â', 'ê', 'î', 'ô', 'û', 'A', 'E', 'I', 'O', 'U', 'Â', 'Ê', 'Î', 'Ô', 'Û'],
  wordlist: [
    'Âjrens',
    'Aszbels',
    'Âtselim',
    'Brassenlâch',
    'Bremurmq',
    'Brôdbens',
    'Burzchêsq',
    'Bzâshamq',
    'Chêmsqarl',
    'Dorzumj',
    'Durndnô',
    'Duzârns',
    'Erqgûrl',
    'Êrsch',
    'Essemqâz',
    'Farshûnt',
    'Freqêrbosq',
    'Funârnq',
    'Gebqêrzq',
    'Glisnânsq',
    'Grobdrin',
    'Gulquârm',
    'Hêmsga',
    'Hôlnulm',
    'Igôchjka',
    'Inorn',
    'Januchm',
    'Jluzsh',
    'Jrôbqa',
    'Karchdûn',
    'Kochmnû',
    'Lojlrâq',
    'Mdrûbna',
    'Mrôjbarm',
    'Murshûl',
    'Nishîmzq',
    'Nurûnz',
    'Oqrêlsh',
    'Ônzdroj',
    'Ordsnôj',
    'Pgûrska',
    'Qrâsch',
    'Qrôshzt',
    'Ramsashûsq',
    'Rbêzj',
    'Rbôndna',
    'Rbûnj',
    'Rsozbqa',
    'Sdrôlgarmq',
    'Shurbûnq',
    'Ubshûrn',
    'Upchqârnu',
    'Urshâmq',
    'Zbrêsh',
    'Zûrnzq',
  ],
};
