export const lenguaDarmuttana = {
  composedWordProbability: 10,
  composedWordMaxTerms: 2,
  diacritics: ['ā', 'ē', 'ī', 'ō', 'ū', 'Ā', 'Ē', 'Ī', 'Ō', 'Ū'],
  diacriticsMaxPerWord: 1,
  diacriticsReversal: {
    ā: 'a',
    ē: 'e',
    ī: 'i',
    ō: 'o',
    ū: 'u',
  },
  interfixes: [
    {
      dataToSend: 'a',
      freq: 'mayor',
    },
    {
      dataToSend: 'an',
      freq: 'relevant',
    },
    {
      dataToSend: 'ar',
      freq: 'low',
    },
    {
      dataToSend: 'az',
      freq: 'minor',
    },
    {
      dataToSend: 'az',
      freq: 'minor',
    },
    {
      dataToSend: 'dol',
      freq: 'rare',
    },
    {
      dataToSend: 'ma',
      freq: 'rare',
    },
    {
      dataToSend: 'na',
      freq: 'rare',
    },
    {
      dataToSend: 'nud',
      freq: 'veryRare',
    },
    {
      dataToSend: 'ran',
      freq: 'veryRare',
    },
    {
      dataToSend: 'ul',
      freq: 'veryRare',
    },
    {
      dataToSend: 'un',
      freq: 'rare',
    },
    {
      dataToSend: 'ur',
      freq: 'rare',
    },
    {
      dataToSend: 'uz',
      freq: 'minor',
    },
  ],
  interfixProbability: 60,
  prefixes: [
    {
      dataToSend: 'ada',
      freq: 'rare',
    },
    {
      dataToSend: 'il',
      freq: 'relevant',
    },
    {
      dataToSend: 'raj',
      freq: 'low',
    },
    {
      dataToSend: 'ur',
      freq: 'relevant',
    },
  ],
  prefixProbability: 5,
  vocals: ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U', 'ā', 'ē', 'ī', 'ō', 'ū', 'Ā', 'Ē', 'Ī', 'Ō', 'Ū'],
  wordlist: [
    'Ajz',
    'Ajšibek',
    'Akral',
    'Alāj',
    'Amrāl',
    'Anankūl',
    'Ankkra',
    'Arbān',
    'Argūn',
    'Aršūn',
    'Ārtamsaj',
    'Ašār',
    'Balāl',
    'Banūn',
    'Barr',
    'Bogaš',
    'Braš',
    'Bulāl',
    'Bun',
    'Bunjadu',
    'Bunna',
    'Burku',
    'Burujpanna',
    'Burūl',
    'Buršulank',
    'Ďar',
    'Dagīl',
    'Dalarsattu',
    'Demja',
    'Dibēš',
    'Dilīl',
    'Dal',
    'Ďakūn',
    'Donšrak',
    'Ďōr',
    'Dor',
    'Dral',
    'Dran',
    'Droj',
    'Druǧa',
    'Dugāl',
    'Ďun',
    'Durr',
    'Ēbelek',
    'Edraš',
    'Elul',
    'Erršūl',
    'Ešra',
    'Fanūn',
    'Fanūr',
    'Farr',
    'Ferūn',
    'Fūnujlarr',
    'Galanddu',
    'Gan',
    'Garsūr',
    'Gilān',
    'Ginu',
    'Ǧodu',
    'Gol',
    'Ǧōralnur',
    'Gorōd',
    'Ǧuda',
    'Gurād',
    'Ibifalūn',
    'Ibrēl',
    'Iddil',
    'Iffa',
    'Ililfanōd',
    'Ilidun',
    'Iktār',
    'Ikufka',
    'Ilāl',
    'Ilalsu',
    'Ilaš',
    'Ilirgūl',
    'Imlej',
    'Ittinǧilga',
    'Innarsu',
    'Ippar',
    'Ipparnūn',
    'Irkippa',
    'Irlaš',
    'Irsaj',
    'Isuzna',
    'Išu',
    'Ittān',
    'Iyiren',
    'Iyunu',
    'Izūn',
    'Jasūr',
    'Jalak',
    'Jelejk',
    'Jradu',
    'Kališa',
    'Ǩan',
    'Kilimnur',
    'Kitta',
    'Kiznu',
    'Ǩrad',
    'Kralur',
    'Krar',
    'Kraš',
    'Kreš',
    'Krin',
    'Kor',
    'Kubāl',
    'Kudna',
    'Kul',
    'Kurandda',
    'Lan',
    'Larkāl',
    'Lod',
    'Lun',
    'Lurduba',
    'Mala',
    'Marēš',
    'Marr',
    'Maširku',
    'Masrāl',
    'Melrāj',
    'Melkanūn',
    'Mugulnōj',
    'Muǧunurttika',
    'Mukrāl',
    'Mutta',
    'Nadna',
    'Naj',
    'Namsūl',
    'Narjaj',
    'Nedu',
    'Niga',
    'Nigīd',
    'Nipa',
    'Nipalila',
    'Nirgungga',
    'Nirsa',
    'Nišur',
    'Nurr',
    'Od’ral',
    'Or',
    'Palakkipra',
    'Par',
    'Purād',
    'Purajkka',
    'Purugunda',
    'Purunjǩaru',
    'Řadda',
    'Rālajmar',
    'Ras',
    'Rašūl',
    'Rubūl',
    'Rujtta',
    'Ruruktta',
    'Rušāj',
    'Šal',
    'Sar',
    'Sarr',
    'Sin',
    'Šomol',
    'Sunūn',
    'Šurattu',
    'Šurǧa',
    'Surta',
    'Timij',
    'Timisār',
    'Turaj',
    'Turr',
    'Tursūd',
    'Ubelilka',
    'Udūl',
    'Udūn',
    'Ujala',
    'Ulāj',
    'Ukād',
    'Ukul',
    'Umrāl',
    'Umurna',
    'Unfād',
    'Unǧutta',
    'Unōr',
    'Unyajtta',
    'Urēk',
    'Ursanašuttu',
    'Var',
    'Zāszra',
    'Zayūr',
  ],
};
