export const lenguaPuiwa = {
  diacritics: ['ä', 'ë', 'ï', 'ö', 'ü'],
  diacriticsMaxPerWord: 1,
  diacriticsReversal: {
    ä: 'a',
    ë: 'e',
    ï: 'i',
    ö: 'o',
    ü: 'u',
  },
  vocals: [
    'a', "ä'w",
    'e',
    'i', 'ie',
    'o', 'oa', 'oe', 'oë',
    'u', 'ua', 'ue', 'uo',
    'w', 'wa', 'we', 'wä', 'wö', "w'ä",
    'y', 'ya', 'yo', 'yoë', 'yowö',
    'A', 'E', 'I', 'O', 'U', 'Ai', 'Aö', 'Ia', "U'i",
    'ä', 'ë', 'ï', 'ö', 'ü',
  ],
  wordlist: [
    'Agoganïte',
    'Alunlonföna',
    "Alungongö'ra",
    'Aonyöre',
    "Aöpe Nga'fäl",
    'Ariransoengoëcha',
    "Cha'nalägo",
    'Charpälle',
    "Choagö'le",
    'Chofäna',
    'Dachagöro',
    "Dambwgä'ligo",
    'Embegëla',
    "Embililaräbu'ro",
    'Farfachäyo',
    'Fawollogönda',
    "Fununchä'wra",
    "Galingan'göro",
    'Gililinanägoro',
    "Gogön'da",
    'Gongangüra',
    'Iachwa',
    'Imporangüra',
    'Ineböno',
    'Insifalönde',
    'Inunamozärka',
    "Iriröm'we",
    'Korkalïsa',
    'Lararomöga',
    'Lurdiagärta',
    'Mzanzöre',
    "Mampochö'ro",
    'Moemboëmde',
    "Mumböra Lalï'ga",
    'Narunanïndu',
    'Nchoenyöro',
    'Ndielelalüma',
    'Nforangö',
    'Ngargäru',
    'Nkuröra',
    'Nwangüa',
    "Nwö'ro",
    "Nkw'ära Nfäno",
    'Ochoära',
    'Ortolalüma',
    "Paranfomë'le",
    "Parnanogalï'mbe",
    "Poa'fwäne",
    'Porwawaläno',
    'Puanyankwa',
    "Ram'wöra",
    'Rarillöra',
    "Ruo'ribëne",
    "Ryoë'la",
    'Talagonägo',
    'Tchöro mo Alu',
    "Tilalimogä'ne",
    "Timela'lünde",
    'Tsisorïngo',
    "Tsupunïtu",
    'Tsuenbebära',
    'Tubengahäla',
    "U'ipöre",
    "Utofü'na",
    "Utsobambö'no",
  ],
};







