export const lenguaCauriana = {
  diacritics: ['à', 'è', 'ì', 'ò', 'ù'],
  diacriticsMaxPerWord: 1,
  diacriticsReversal: {
    à: 'a',
    è: 'e',
    ì: 'i',
    ò: 'o',
    ù: 'u',
  },
  vocals: ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U', 'Ai', 'y', 'à', 'è', 'ì', 'ò', 'ù', 'yò', 'ài'],
  wordlist: [
    'Ahabendur',
    'Azsel',
    'Barsgesdzàr',
    'Bàzte',
    'Beleheszàd',
    'Caporhài',
    'Cihan',
    'Cobrosenc',
    'Coron',
    'Cunahìrna',
    'Demerseld',
    'Doronbàr',
    'Eronhìba',
    'Fahala',
    'Fanynhadùn',
    'Fehègebed',
    'Ferzenbac',
    'Gazahòr',
    'Gorzahand',
    'Harzdùna',
    'Imoztal',
    'Inangyra',
    'Iszahadar',
    'Iszìztibel',
    'Izgyòrd',
    'Mahabore',
    'Meztòre',
    'Mobohalizsa',
    'Mozbron',
    'Muszaragòr',
    'Nyrpàl',
    'Pabadgùl',
    'Parfalìne',
    'Parhàzte',
    'Samazsùl',
    'Sangyhazsài',
    'Szegelindur',
    'Szendur',
    'Szenfahad',
    'Tarhagalàdta',
    'Tihald',
    'Turhybalàd',
    'Tzerszèna',
    'Zsendel',
    'Zubenhazd',
    'Zuhundàl',
  ],
};







